### ISSUE TITLE
Todo of basic

### ISSUE THREAD

**Issue by cookie777** [cookie777/ForEach-Item#36]
- [ ] add each section
- [ ] pass image path
- [ ] create components to reduce repetitive div
- [ ] gather all imgaURL and text data in data.js
- [ ] iterate and pass those data into component

**Comment by cookie777** [comment]
> * [ ]  add each section
> * [ ]  pass image path
> * [ ]  create components to reduce repetitive div
> * [ ]  gather all imgaURL and text data in data.js
> * [ ]  iterate and pass those data into component
